"""
https://github.com/dorinemerlat/EXOGAP

Snakefile to run EXOGAP
-----------------------------------------

Requirements:
 - SnakeMake (http://snakemake.readthedocs.io/en/stable/)

Basic usage:
  snakemake -p \
    --configfile config.yaml \
    -j 64 

Author:
  Dorine MERLAT

Contact:
  dorine.merlat@etu.unistra.fr  

License:
  GNU General Public License
"""

import os

